# Generated by Django 5.1 on 2026-03-14 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('amount_kobo', models.PositiveIntegerField()),
                ('fund_choice', models.CharField(choices=[('VICTIM', 'Victim Relief — goes to the affected person or family'), ('RESPONDER', 'First Responder Appreciation — split equally among responders on scene'), ('PLATFORM', 'Emergency Response Fund — keeps Siren running')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('paystack_reference', models.CharField(max_length=200, unique=True)),
                ('paystack_response', models.JSONField(default=dict)),
                ('recipient_subaccount', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TRANSPORT', 'Transport (car, bike, keke)'), ('EQUIPMENT', 'Equipment (ladder, generator, rope, torch)'), ('MEDICAL', 'Medical (first aid kit, stretcher, oxygen)'), ('FOOD_WATER', 'Food and Water'), ('MANPOWER', 'Manpower (extra hands needed)'), ('OTHER', 'Other')], max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('NEEDED', 'Needed'), ('CLAIMED', 'Claimed'), ('ARRIVED', 'Arrived')], default='NEEDED', max_length=10)),
                ('suggested_by_hash', models.CharField(max_length=64)),
                ('suggested_by_name', models.CharField(blank=True, max_length=100)),
                ('suggested_via', models.CharField(choices=[('WEB', 'Web'), ('WHATSAPP', 'WhatsApp')], default='WEB', max_length=20)),
                ('confirmed_by_hash', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='incidents.incident')),
            ],
            options={
                'ordering': ['status', 'category', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimer_hash', models.CharField(max_length=64)),
                ('claimer_name', models.CharField(blank=True, max_length=100)),
                ('claimer_phone', models.CharField(blank=True, max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='resources.resourceitem')),
            ],
            options={
                'unique_together': {('resource', 'claimer_hash')},
            },
        ),
    ]
