# Generated by Django 5.1 on 2026-03-14 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone_hash', models.CharField(max_length=64, unique=True)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('skill_category', models.CharField(choices=[('MED_ADV', 'Medical Advanced (Doctor/Surgeon)'), ('MED_BASIC', 'Medical Basic (Nurse/Paramedic)'), ('FIRE', 'Fire Response'), ('WATER', 'Water/Flood Rescue'), ('STRUCTURAL', 'Structural Rescue/Engineer'), ('ELECTRICAL', 'Electrical (Licensed)'), ('FIRST_AID', 'First Aid/CPR Certified')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=15)),
                ('licence_number', models.CharField(blank=True, max_length=100)),
                ('home_lat', models.FloatField()),
                ('home_lng', models.FloatField()),
                ('response_radius_km', models.FloatField(default=2.0)),
                ('is_available', models.BooleanField(default=False)),
                ('responds_to', models.JSONField(default=list)),
                ('total_responses', models.PositiveIntegerField(default=0)),
                ('zone_name', models.CharField(blank=True, max_length=100)),
                ('paystack_subaccount', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponderDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(null=True)),
                ('on_scene_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responder_dispatches', to='incidents.incident')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='responders.responder')),
            ],
            options={
                'unique_together': {('responder', 'incident')},
            },
        ),
    ]
