# Generated by Django 5.1 on 2026-03-14 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_hash', models.CharField(max_length=64)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('HOME', 'Home'), ('SCHOOL', 'School/Child location'), ('LAND', 'Land/Property'), ('OFFICE', 'Office/Workplace'), ('FAMILY', 'Family member location'), ('OTHER', 'Other')], default='HOME', max_length=10)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('address_text', models.CharField(blank=True, max_length=500)),
                ('alert_radius_km', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('incident_types', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_alerts', to='incidents.incident')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='subscriptions.locationsubscription')),
            ],
            options={
                'unique_together': {('subscription', 'incident')},
            },
        ),
    ]
