# Generated by Django 5.1 on 2026-03-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsubscription',
            name='address_text',
        ),
        migrations.AddField(
            model_name='locationsubscription',
            name='commute_buffer_km',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='locationsubscription',
            name='family_members',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='locationsubscription',
            name='office_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationsubscription',
            name='office_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationsubscription',
            name='peak_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locationsubscription',
            name='safety_score',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='locationsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('POINT', 'Single Point — Guardian Mode'), ('COMMUTE', 'Commute Shield — Home + Office corridor')], default='POINT', max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionalert',
            name='alert_type',
            field=models.CharField(choices=[('POINT', 'Point'), ('COMMUTE', 'Commute')], default='POINT', max_length=10),
        ),
        migrations.CreateModel(
            name='SafetyScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='subscriptions.locationsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
