# Generated by Django 5.1 on 2026-05-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_lgasubscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lgasubscription',
            new_name='subscriptio_lga_a7c18e_idx',
            old_name='sub_lga_active_idx',
        ),
        migrations.RenameIndex(
            model_name='lgasubscription',
            new_name='subscriptio_user_id_6e6520_idx',
            old_name='sub_user_active_idx',
        ),
    ]
