# Generated by Django 5.1 on 2026-03-12 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('WEB', 'Web Portal')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=200)),
                ('reporter_hash', models.CharField(max_length=64)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('incident_type', models.CharField(blank=True, choices=[('FIRE', 'Fire Outbreak'), ('FLOOD', 'Flooding'), ('COLLAPSE', 'Building/Structural Collapse'), ('RTA', 'Road Traffic Accident'), ('EXPLOSION', 'Gas/Chemical Explosion'), ('DROWNING', 'Drowning/Water Emergency'), ('HAZARD', 'Structural/Electrical Hazard')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('VERIFYING', 'Verifying'), ('VERIFIED', 'Verified'), ('RESPONDING', 'Community Responding'), ('AGENCY_NOTIFIED', 'Agency Notified'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='DETECTED', max_length=20)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('address_text', models.CharField(blank=True, max_length=500)),
                ('zone_name', models.CharField(blank=True, max_length=100)),
                ('media_urls', models.JSONField(default=list)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('ai_raw_response', models.JSONField(default=dict)),
                ('vouch_count', models.PositiveIntegerField(default=0)),
                ('vouch_threshold', models.PositiveIntegerField(default=3)),
                ('total_donations_kobo', models.PositiveIntegerField(default=0)),
                ('donation_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('agency_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('actor', models.CharField(max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_logs', to='incidents.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VouchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(max_length=64)),
                ('voucher_lat', models.FloatField(blank=True, null=True)),
                ('voucher_lng', models.FloatField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('WHATSAPP', 'WhatsApp reaction')], default='WEB', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouches', to='incidents.incident')),
            ],
            options={
                'unique_together': {('incident', 'session_hash')},
            },
        ),
    ]
