# Generated by Django 5.1 on 2026-03-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='is_infrastructure',
            field=models.BooleanField(default=False),
        ),
    ]
