# Generated by Django 5.1 on 2026-03-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_is_infrastructure'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('public_url', models.URLField(max_length=500)),
                ('storage_path', models.CharField(max_length=500)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_by_hash', models.CharField(blank=True, max_length=64)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='incidents.incident')),
            ],
            options={
                'ordering': ['upload_timestamp'],
            },
        ),
    ]
