# Generated by Django 5.1 on 2026-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incidentmedia'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='casualties',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='date_occurred',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='injuries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_historical',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='lga',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='incident',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='incident',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('WEB', 'Web Portal'), ('NEWS_SCRAPE', 'News Scrape')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['zone_name', 'status'], name='incidents_i_zone_na_356189_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['lga', 'status'], name='incidents_i_lga_752cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['is_historical', 'status'], name='incidents_i_is_hist_4ad206_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['date_occurred'], name='incidents_i_date_oc_518294_idx'),
        ),
    ]
