# Generated by Django 5.1 on 2026-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_historical_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentmedia',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('url', 'External URL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='public_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='storage_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
