# Generated by Django 5.1 on 2026-05-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_incidentmedia_caption_nullable_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
