# Generated by Django 5.2.17 on 2026-09-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_increase_reporter_phone_max_length'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='coordinator_note',
            field=models.TextField(blank=True, default='', help_text='Internal. Never sent to the reporter.'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'created_at'], name='incidents_i_status_5d0930_idx'),
        ),
    ]
