# Generated by Django 5.1 on 2026-03-12 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('org_type', models.CharField(choices=[('HOSPITAL', 'Hospital/Clinic'), ('AMBULANCE', 'Ambulance Service'), ('PHARMACY', 'Pharmacy'), ('TOWING', 'Towing/Heavy Equipment'), ('FIRE_SAFETY', 'Fire Safety Company'), ('NGO', 'NGO/Community Group'), ('AGENCY', 'Government Agency'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=15)),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
                ('address', models.CharField(max_length=500)),
                ('zone_name', models.CharField(blank=True, max_length=100)),
                ('response_radius_km', models.FloatField(default=5.0)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_whatsapp', models.CharField(max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('responds_to', models.JSONField(default=list)),
                ('operating_hours', models.CharField(default='24/7', max_length=200)),
                ('cac_number', models.CharField(blank=True, max_length=100)),
                ('total_responses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dashboard_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
